/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { ApiV1AuthWebauthnLoginAuthenticatePost200Response } from '../model/api-v1-auth-webauthn-login-authenticate-post200-response';
// @ts-ignore
import { ApiV1AuthWebauthnLoginAuthenticatePost404Response } from '../model/api-v1-auth-webauthn-login-authenticate-post404-response';
// @ts-ignore
import { ApiV1AuthWebauthnLoginAuthenticatePostRequest } from '../model/api-v1-auth-webauthn-login-authenticate-post-request';
// @ts-ignore
import { ApiV1AuthWebauthnLoginOptionsPost200Response } from '../model/api-v1-auth-webauthn-login-options-post200-response';
// @ts-ignore
import { ApiV1AuthWebauthnLoginOptionsPost404Response } from '../model/api-v1-auth-webauthn-login-options-post404-response';
// @ts-ignore
import { ApiV1AuthWebauthnLoginOptionsPostRequest } from '../model/api-v1-auth-webauthn-login-options-post-request';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    AuthenticationServiceInterface,
    ApiV1AuthWebauthnLoginAuthenticatePostRequestParams,
    ApiV1AuthWebauthnLoginOptionsPostRequestParams
} from './authentication.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class AuthenticationService extends BaseService implements AuthenticationServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Authenticate with WebAuthn
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1AuthWebauthnLoginAuthenticatePost(requestParameters?: ApiV1AuthWebauthnLoginAuthenticatePostRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiV1AuthWebauthnLoginAuthenticatePost200Response>;
    public apiV1AuthWebauthnLoginAuthenticatePost(requestParameters?: ApiV1AuthWebauthnLoginAuthenticatePostRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiV1AuthWebauthnLoginAuthenticatePost200Response>>;
    public apiV1AuthWebauthnLoginAuthenticatePost(requestParameters?: ApiV1AuthWebauthnLoginAuthenticatePostRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiV1AuthWebauthnLoginAuthenticatePost200Response>>;
    public apiV1AuthWebauthnLoginAuthenticatePost(requestParameters?: ApiV1AuthWebauthnLoginAuthenticatePostRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const apiV1AuthWebauthnLoginAuthenticatePostRequest = requestParameters?.apiV1AuthWebauthnLoginAuthenticatePostRequest;

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/auth/webauthn/login/authenticate`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiV1AuthWebauthnLoginAuthenticatePost200Response>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: apiV1AuthWebauthnLoginAuthenticatePostRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get WebAuthn login options
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1AuthWebauthnLoginOptionsPost(requestParameters?: ApiV1AuthWebauthnLoginOptionsPostRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiV1AuthWebauthnLoginOptionsPost200Response>;
    public apiV1AuthWebauthnLoginOptionsPost(requestParameters?: ApiV1AuthWebauthnLoginOptionsPostRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiV1AuthWebauthnLoginOptionsPost200Response>>;
    public apiV1AuthWebauthnLoginOptionsPost(requestParameters?: ApiV1AuthWebauthnLoginOptionsPostRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiV1AuthWebauthnLoginOptionsPost200Response>>;
    public apiV1AuthWebauthnLoginOptionsPost(requestParameters?: ApiV1AuthWebauthnLoginOptionsPostRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const apiV1AuthWebauthnLoginOptionsPostRequest = requestParameters?.apiV1AuthWebauthnLoginOptionsPostRequest;

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/auth/webauthn/login/options`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiV1AuthWebauthnLoginOptionsPost200Response>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: apiV1AuthWebauthnLoginOptionsPostRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
