/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiV1AuthWebauthnLoginAuthenticatePost200Response } from '../model/models';
import { ApiV1AuthWebauthnLoginAuthenticatePost404Response } from '../model/models';
import { ApiV1AuthWebauthnLoginAuthenticatePostRequest } from '../model/models';
import { ApiV1AuthWebauthnLoginOptionsPost200Response } from '../model/models';
import { ApiV1AuthWebauthnLoginOptionsPost404Response } from '../model/models';
import { ApiV1AuthWebauthnLoginOptionsPostRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiV1AuthWebauthnLoginAuthenticatePostRequestParams {
    apiV1AuthWebauthnLoginAuthenticatePostRequest?: ApiV1AuthWebauthnLoginAuthenticatePostRequest;
}

export interface ApiV1AuthWebauthnLoginOptionsPostRequestParams {
    apiV1AuthWebauthnLoginOptionsPostRequest?: ApiV1AuthWebauthnLoginOptionsPostRequest;
}


export interface AuthenticationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Authenticate with WebAuthn
     * 
* @param requestParameters
     */
    apiV1AuthWebauthnLoginAuthenticatePost(requestParameters: ApiV1AuthWebauthnLoginAuthenticatePostRequestParams, extraHttpRequestParams?: any): Observable<ApiV1AuthWebauthnLoginAuthenticatePost200Response>;

    /**
     * Get WebAuthn login options
     * 
* @param requestParameters
     */
    apiV1AuthWebauthnLoginOptionsPost(requestParameters: ApiV1AuthWebauthnLoginOptionsPostRequestParams, extraHttpRequestParams?: any): Observable<ApiV1AuthWebauthnLoginOptionsPost200Response>;

}
