/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { ApiV1AuthWebauthnLoginOptionsPost404Response } from '../model/api-v1-auth-webauthn-login-options-post404-response';
// @ts-ignore
import { ApiV1ProjectsProjectIdBuildMetricsGet200Response } from '../model/api-v1-projects-project-id-build-metrics-get200-response';
// @ts-ignore
import { ApiV1ProjectsProjectIdBuildMetricsPost201Response } from '../model/api-v1-projects-project-id-build-metrics-post201-response';
// @ts-ignore
import { ApiV1ProjectsProjectIdBuildMetricsPostRequest } from '../model/api-v1-projects-project-id-build-metrics-post-request';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    BuildMetricsServiceInterface,
    ApiV1ProjectsProjectIdBuildMetricsGetRequestParams,
    ApiV1ProjectsProjectIdBuildMetricsPostRequestParams
} from './build-metrics.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class BuildMetricsService extends BaseService implements BuildMetricsServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Get build metrics for a project
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1ProjectsProjectIdBuildMetricsGet(requestParameters: ApiV1ProjectsProjectIdBuildMetricsGetRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiV1ProjectsProjectIdBuildMetricsGet200Response>;
    public apiV1ProjectsProjectIdBuildMetricsGet(requestParameters: ApiV1ProjectsProjectIdBuildMetricsGetRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiV1ProjectsProjectIdBuildMetricsGet200Response>>;
    public apiV1ProjectsProjectIdBuildMetricsGet(requestParameters: ApiV1ProjectsProjectIdBuildMetricsGetRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiV1ProjectsProjectIdBuildMetricsGet200Response>>;
    public apiV1ProjectsProjectIdBuildMetricsGet(requestParameters: ApiV1ProjectsProjectIdBuildMetricsGetRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const projectId = requestParameters?.projectId;
        if (projectId === null || projectId === undefined) {
            throw new Error('Required parameter projectId was null or undefined when calling apiV1ProjectsProjectIdBuildMetricsGet.');
        }
        const interval = requestParameters?.interval;
        const environment = requestParameters?.environment;
        const startTime = requestParameters?.startTime;
        const endTime = requestParameters?.endTime;

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>interval, 'interval');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>environment, 'environment');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>startTime, 'start_time');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>endTime, 'end_time');

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/projects/${this.configuration.encodeParam({name: "projectId", value: projectId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: undefined})}/build_metrics`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiV1ProjectsProjectIdBuildMetricsGet200Response>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create build metrics
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1ProjectsProjectIdBuildMetricsPost(requestParameters: ApiV1ProjectsProjectIdBuildMetricsPostRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiV1ProjectsProjectIdBuildMetricsPost201Response>;
    public apiV1ProjectsProjectIdBuildMetricsPost(requestParameters: ApiV1ProjectsProjectIdBuildMetricsPostRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiV1ProjectsProjectIdBuildMetricsPost201Response>>;
    public apiV1ProjectsProjectIdBuildMetricsPost(requestParameters: ApiV1ProjectsProjectIdBuildMetricsPostRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiV1ProjectsProjectIdBuildMetricsPost201Response>>;
    public apiV1ProjectsProjectIdBuildMetricsPost(requestParameters: ApiV1ProjectsProjectIdBuildMetricsPostRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const projectId = requestParameters?.projectId;
        if (projectId === null || projectId === undefined) {
            throw new Error('Required parameter projectId was null or undefined when calling apiV1ProjectsProjectIdBuildMetricsPost.');
        }
        const apiV1ProjectsProjectIdBuildMetricsPostRequest = requestParameters?.apiV1ProjectsProjectIdBuildMetricsPostRequest;

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/projects/${this.configuration.encodeParam({name: "projectId", value: projectId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: undefined})}/build_metrics`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiV1ProjectsProjectIdBuildMetricsPost201Response>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: apiV1ProjectsProjectIdBuildMetricsPostRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
