/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiV1AuthWebauthnLoginOptionsPost404Response } from '../model/models';
import { ApiV1ProjectsProjectIdBuildMetricsGet200Response } from '../model/models';
import { ApiV1ProjectsProjectIdBuildMetricsPost201Response } from '../model/models';
import { ApiV1ProjectsProjectIdBuildMetricsPostRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiV1ProjectsProjectIdBuildMetricsGetRequestParams {
    projectId: number;
    interval?: '1m' | '5m' | '15m' | '30m' | '1h' | '6h' | '12h' | '1d';
    environment?: string;
    startTime?: string;
    endTime?: string;
}

export interface ApiV1ProjectsProjectIdBuildMetricsPostRequestParams {
    projectId: number;
    apiV1ProjectsProjectIdBuildMetricsPostRequest?: ApiV1ProjectsProjectIdBuildMetricsPostRequest;
}


export interface BuildMetricsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get build metrics for a project
     * 
* @param requestParameters
     */
    apiV1ProjectsProjectIdBuildMetricsGet(requestParameters: ApiV1ProjectsProjectIdBuildMetricsGetRequestParams, extraHttpRequestParams?: any): Observable<ApiV1ProjectsProjectIdBuildMetricsGet200Response>;

    /**
     * Create build metrics
     * 
* @param requestParameters
     */
    apiV1ProjectsProjectIdBuildMetricsPost(requestParameters: ApiV1ProjectsProjectIdBuildMetricsPostRequestParams, extraHttpRequestParams?: any): Observable<ApiV1ProjectsProjectIdBuildMetricsPost201Response>;

}
