/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiV1FilesWithViolationsGet200Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiV1FilesWithViolationsGetRequestParams {
    page?: number;
    perPage?: number;
    analysisJobId?: number;
    filePath?: string;
    ruleName?: string;
    sort?: string;
    direction?: string;
}


export interface FilesWithViolationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Lists files with violations
     * 
* @param requestParameters
     */
    apiV1FilesWithViolationsGet(requestParameters: ApiV1FilesWithViolationsGetRequestParams, extraHttpRequestParams?: any): Observable<ApiV1FilesWithViolationsGet200Response>;

}
