/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiV1ProjectsProjectIdRulesGet200Response } from '../model/models';
import { ApiV1ProjectsProjectIdRulesIdPatchRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiV1ProjectsProjectIdRulesGetRequestParams {
    projectId: number;
}

export interface ApiV1ProjectsProjectIdRulesIdPatchRequestParams {
    projectId: number;
    id: number;
    apiV1ProjectsProjectIdRulesIdPatchRequest?: ApiV1ProjectsProjectIdRulesIdPatchRequest;
}

export interface ToggleRuleRequestParams {
    projectId: number;
    id: number;
}


export interface ProjectRulesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Lists all rules for a project
     * 
* @param requestParameters
     */
    apiV1ProjectsProjectIdRulesGet(requestParameters: ApiV1ProjectsProjectIdRulesGetRequestParams, extraHttpRequestParams?: any): Observable<ApiV1ProjectsProjectIdRulesGet200Response>;

    /**
     * Updates a rule\&#39;s status for a project
     * 
* @param requestParameters
     */
    apiV1ProjectsProjectIdRulesIdPatch(requestParameters: ApiV1ProjectsProjectIdRulesIdPatchRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * toggle
     * 
* @param requestParameters
     */
    toggleRule(requestParameters: ToggleRuleRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
