/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiV1RuleGroupsGet200Response } from '../model/models';
import { ApiV1RuleGroupsIdAddRulesPostRequest } from '../model/models';
import { ApiV1RuleGroupsIdGet200Response } from '../model/models';
import { ApiV1RuleGroupsIdPatchRequest } from '../model/models';
import { ApiV1RuleGroupsPostRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiV1RuleGroupsIdAddRulesPostRequestParams {
    id: number;
    apiV1RuleGroupsIdAddRulesPostRequest?: ApiV1RuleGroupsIdAddRulesPostRequest;
}

export interface ApiV1RuleGroupsIdDeleteRequestParams {
    id: number;
}

export interface ApiV1RuleGroupsIdGetRequestParams {
    id: number;
}

export interface ApiV1RuleGroupsIdPatchRequestParams {
    id: number;
    apiV1RuleGroupsIdPatchRequest?: ApiV1RuleGroupsIdPatchRequest;
}

export interface ApiV1RuleGroupsIdRulesRuleIdDeleteRequestParams {
    id: number;
    ruleId: number;
}

export interface ApiV1RuleGroupsPostRequestParams {
    apiV1RuleGroupsPostRequest?: ApiV1RuleGroupsPostRequest;
}


export interface RuleGroupsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Lists all rule groups
     * 
*/
    apiV1RuleGroupsGet(extraHttpRequestParams?: any): Observable<ApiV1RuleGroupsGet200Response>;

    /**
     * Adds rules to a group
     * 
* @param requestParameters
     */
    apiV1RuleGroupsIdAddRulesPost(requestParameters: ApiV1RuleGroupsIdAddRulesPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Deletes a rule group
     * 
* @param requestParameters
     */
    apiV1RuleGroupsIdDelete(requestParameters: ApiV1RuleGroupsIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Retrieves a rule group
     * 
* @param requestParameters
     */
    apiV1RuleGroupsIdGet(requestParameters: ApiV1RuleGroupsIdGetRequestParams, extraHttpRequestParams?: any): Observable<ApiV1RuleGroupsIdGet200Response>;

    /**
     * Updates a rule group
     * 
* @param requestParameters
     */
    apiV1RuleGroupsIdPatch(requestParameters: ApiV1RuleGroupsIdPatchRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Removes a rule from a group
     * 
* @param requestParameters
     */
    apiV1RuleGroupsIdRulesRuleIdDelete(requestParameters: ApiV1RuleGroupsIdRulesRuleIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Creates a rule group
     * 
* @param requestParameters
     */
    apiV1RuleGroupsPost(requestParameters: ApiV1RuleGroupsPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
