/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiV1RulesGet200ResponseInner } from '../model/models';
import { ApiV1RulesIdGet200Response } from '../model/models';
import { ApiV1RulesIdPatchRequest } from '../model/models';
import { ApiV1RulesPostRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiV1RulesIdDeleteRequestParams {
    id: number;
}

export interface ApiV1RulesIdGetRequestParams {
    id: number;
}

export interface ApiV1RulesIdPatchRequestParams {
    id: number;
    apiV1RulesIdPatchRequest?: ApiV1RulesIdPatchRequest;
}

export interface ApiV1RulesPostRequestParams {
    apiV1RulesPostRequest?: ApiV1RulesPostRequest;
}


export interface RulesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Lists all rules
     * 
*/
    apiV1RulesGet(extraHttpRequestParams?: any): Observable<Array<ApiV1RulesGet200ResponseInner>>;

    /**
     * Deletes a rule
     * 
* @param requestParameters
     */
    apiV1RulesIdDelete(requestParameters: ApiV1RulesIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Retrieves a rule
     * 
* @param requestParameters
     */
    apiV1RulesIdGet(requestParameters: ApiV1RulesIdGetRequestParams, extraHttpRequestParams?: any): Observable<ApiV1RulesIdGet200Response>;

    /**
     * Updates a rule
     * 
* @param requestParameters
     */
    apiV1RulesIdPatch(requestParameters: ApiV1RulesIdPatchRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Creates a rule
     * 
* @param requestParameters
     */
    apiV1RulesPost(requestParameters: ApiV1RulesPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
