/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiV1AnalysisJobsAnalysisJobIdViolationsGet200Response } from '../model/models';
import { ApiV1ViolationsGet200Response } from '../model/models';
import { ApiV1ViolationsTimeSeriesGet200Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiV1AnalysisJobsAnalysisJobIdViolationsGetRequestParams {
    analysisJobId: number;
    page?: number;
    perPage?: number;
    ruleName?: string;
    ruleId?: string;
    filePath?: string;
}

export interface ApiV1AnalysisJobsAnalysisJobIdViolationsTimeSeriesGetRequestParams {
    analysisJobId: number;
    startDate?: string;
    endDate?: string;
    ruleId?: string;
    ruleName?: string;
}

export interface ApiV1ViolationsGetRequestParams {
    page?: number;
    perPage?: number;
    ruleName?: string;
    ruleId?: string;
    analysisJobId?: number;
    filePath?: string;
}

export interface ApiV1ViolationsTimeSeriesGetRequestParams {
    startDate?: string;
    endDate?: string;
    ruleId?: string;
    ruleName?: string;
    analysisJobId?: number;
}


export interface ViolationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Lists violations for an analysis job
     * 
* @param requestParameters
     */
    apiV1AnalysisJobsAnalysisJobIdViolationsGet(requestParameters: ApiV1AnalysisJobsAnalysisJobIdViolationsGetRequestParams, extraHttpRequestParams?: any): Observable<ApiV1AnalysisJobsAnalysisJobIdViolationsGet200Response>;

    /**
     * Gets time series data for violations in an analysis job
     * 
* @param requestParameters
     */
    apiV1AnalysisJobsAnalysisJobIdViolationsTimeSeriesGet(requestParameters: ApiV1AnalysisJobsAnalysisJobIdViolationsTimeSeriesGetRequestParams, extraHttpRequestParams?: any): Observable<ApiV1ViolationsTimeSeriesGet200Response>;

    /**
     * Lists all violations
     * 
* @param requestParameters
     */
    apiV1ViolationsGet(requestParameters: ApiV1ViolationsGetRequestParams, extraHttpRequestParams?: any): Observable<ApiV1ViolationsGet200Response>;

    /**
     * Gets time series data for violations
     * 
* @param requestParameters
     */
    apiV1ViolationsTimeSeriesGet(requestParameters: ApiV1ViolationsTimeSeriesGetRequestParams, extraHttpRequestParams?: any): Observable<ApiV1ViolationsTimeSeriesGet200Response>;

}
