name: Scoper Action
description: Run scoper v0.1.2 on repository code

inputs:
  args:
    description: "Arguments to pass to scoper when executing"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Cache scoper binary
      id: cache-scoper
      uses: actions/cache@v4
      with:
        path: ${{ github.action_path }}/scoper # Path to cache
        key: ${{ runner.os }}-scoper-v0.1.2 # Cache key

    - name: Download scoper binary if not cached
      if: steps.cache-scoper.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Downloading scoper v0.1.2..."
        curl -L -o ${{ github.action_path }}/scoper https://github.com/rryter/sentinel/releases/download/v0.1.2/scoper

    - name: Download rules.json
      shell: bash
      run: |
        echo "Downloading rules.json..."
        curl -fSL -o ${{ github.action_path }}/rules.json https://raw.githubusercontent.com/rryter/sentinel/main/sentinel-analysis/rules.json

    - name: Make scoper binary executable
      shell: bash
      run: chmod +x ${{ github.action_path }}/scoper

    - name: Run scoper on repository code
      shell: bash
      run: ${{ github.action_path }}/scoper ${{ inputs.args }}
