name: Scoper Action
description: Run scoper v0.1.2 on repository code

inputs:
  args:
    description: 'Arguments to pass to scoper when executing'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install scoper using actions-rs/install
      uses: actions-rs/install@v0.1
      with:
        crate: scoper
        version: 0.1.2
        use-tool-cache: true

    - name: Run scoper on repository code
      shell: bash
      run: scoper ${{ inputs.args }}