[package]
name = "typescript-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
walkdir = "2.4"
anyhow = "1.0"
colored = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.10.2"
# For the future integration with oxc parser
oxc_allocator = "0.62.0"
oxc_parser = "0.62.0"
oxc_ast = "0.62.0"
oxc_span = "0.62.0"
# For parallel processing
rayon = "1.8"
# For faster memory allocation
mimalloc = { version = "0.1", default-features = false }
# For a global allocator wrapper
once_cell = "1.18"
# For async file I/O (optional)
tokio = { version = "1", features = ["full"] }
parking_lot = "0.12.3"
log = "0.4.27"
serde_yaml = "0.9"
