default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: "127.0.0.1"
  port: 3306

development:
  <<: *default
  database: sentinel_backend_development

test:
  <<: *default
  database: sentinel_backend_test

production:
  <<: *default
  database: sentinel_backend_production
  username: sentinel
  password: <%= ENV['SENTINEL_DATABASE_PASSWORD'] %>
