default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rryter
  password: 12345678
  host: localhost

development:
  <<: *default
  database: sentinel_backend_development

test:
  <<: *default
  database: sentinel_backend_test

production:
  <<: *default
  database: sentinel_backend_production
  username: sentinel
  password: <%= ENV['SENTINEL_DATABASE_PASSWORD'] %>