import { Provider } from '@angular/core';
import { provideIcons as ngProvideIcons } from '@ng-icons/core';
import {
  lucideArrowDown,
  lucideArrowLeft,
  lucideArrowRight,
  lucideBookmark,
  lucideCalendar,
  lucideCheck,
  lucideChevronDown,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronUp,
  lucideCircle,
  lucideCircleCheck,
  lucideClock,
  lucideEllipsis,
  lucideFile,
  lucideFolders,
  lucideHammer,
  lucideInfo,
  lucideLayoutGrid,
  lucideScroll,
  lucideSearch,
  lucideSettings,
  lucideX,
} from '@ng-icons/lucide';

export function provideIcons(): Provider[] {
  return [
    ngProvideIcons({
      lucideArrowDown,
      lucideArrowLeft,
      lucideArrowRight,
      lucideBookmark,
      lucideCalendar,
      lucideCheck,
      lucideChevronDown,
      lucideChevronLeft,
      lucideChevronRight,
      lucideChevronUp,
      lucideCircle,
      lucideClock,
      lucideEllipsis,
      lucideFile,
      lucideInfo,
      lucideLayoutGrid,
      lucideX,
      lucideFolders,
      lucideScroll,
      lucideSearch,
      lucideCircleCheck,
      lucideHammer,
      lucideSettings,
    }),
  ];
}
