/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnalysisJob { 
    id: number;
    project_id: number;
    status: AnalysisJobStatusEnum;
    created_at?: string;
    updated_at?: string;
}
export enum AnalysisJobStatusEnum {
    PENDING = 'pending',
    RUNNING = 'running',
    COMPLETED = 'completed',
    FAILED = 'failed'
};




