/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1ProjectsPost201ResponseData } from './api-v1-projects-post201-response-data';


export interface ApiV1ProjectsPost201Response { 
    data: ApiV1ProjectsPost201ResponseData;
    meta?: any | null;
}


