/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiV1RuleGroupsGet200ResponseRuleGroupsInnerRulesInner { 
    id?: number;
    name?: string;
    description?: string;
}


