/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1RuleGroupsPostRequestRuleGroup } from './api-v1-rule-groups-post-request-rule-group';


export interface ApiV1RuleGroupsPostRequest { 
    rule_group?: ApiV1RuleGroupsPostRequestRuleGroup;
}


