/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1AnalysisJobsGet200ResponseDataInner } from './api-v1-analysis-jobs-get200-response-data-inner';


export interface ApiV1AnalysisJobsPost201Response { 
    data: ApiV1AnalysisJobsGet200ResponseDataInner;
}


