/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1ExamplesPostRequest } from './api-v1-examples-post-request';


export interface ApiV1RulesPostRequest { 
    rule?: ApiV1ExamplesPostRequest;
}


