/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1AnalysisJobsRuleHistoryGet200ResponseDataInnerRulesInner } from './api-v1-analysis-jobs-rule-history-get200-response-data-inner-rules-inner';


export interface ApiV1AnalysisJobsRuleHistoryGet200ResponseDataInner { 
    job_id: number;
    created_at: string;
    completed_at: string;
    total_files: number;
    total_violations: number;
    rules: Array<ApiV1AnalysisJobsRuleHistoryGet200ResponseDataInnerRulesInner>;
}


