/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiV1AnalysisJobsGet200ResponseDataInnerProject { 
    id: number;
    name: string;
    repository_url: string;
    created_at: string;
    updated_at: string;
}


