/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1ProjectsProjectIdBuildMetricsPostRequestMetricsInner } from './api-v1-projects-project-id-build-metrics-post-request-metrics-inner';


export interface ApiV1ProjectsProjectIdBuildMetricsPostRequest { 
    metrics: Array<ApiV1ProjectsProjectIdBuildMetricsPostRequestMetricsInner>;
}


