/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1ProjectsGet200ResponseDataProjectsInner } from './api-v1-projects-get200-response-data-projects-inner';


export interface ApiV1ProjectsGet200ResponseData { 
    projects: Array<ApiV1ProjectsGet200ResponseDataProjectsInner>;
}


