/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiV1FilesWithViolationsGet200ResponseMeta { 
    total_count?: number;
    current_page?: number;
    total_pages?: number;
    sort?: string;
    direction?: string;
}


