/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1RulesGet200ResponseRulesInner } from './api-v1-rules-get200-response-rules-inner';


export interface ApiV1RulesGet200Response { 
    rules: Array<ApiV1RulesGet200ResponseRulesInner>;
}


