/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1AuthWebauthnLoginOptionsPost200ResponseAllowCredentialsInner } from './api-v1-auth-webauthn-login-options-post200-response-allow-credentials-inner';


export interface ApiV1AuthWebauthnLoginOptionsPost200Response { 
    challenge?: string;
    rp_id?: string;
    allowCredentials?: Array<ApiV1AuthWebauthnLoginOptionsPost200ResponseAllowCredentialsInner>;
}


