/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiV1AnalysisJobsRuleHistoryGet200ResponseDataInnerRulesInner { 
    rule_name: string;
    violations_count: number;
}


