/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1RuleGroupsIdPatchRequestRuleGroup } from './api-v1-rule-groups-id-patch-request-rule-group';


export interface ApiV1RulesIdPatchRequest { 
    rule?: ApiV1RuleGroupsIdPatchRequestRuleGroup;
}


