/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1ViolationsGet200ResponseDataInner } from './api-v1-violations-get200-response-data-inner';
import { ApiV1AnalysisJobsAnalysisJobIdViolationsGet200ResponseMeta } from './api-v1-analysis-jobs-analysis-job-id-violations-get200-response-meta';


export interface ApiV1AnalysisJobsAnalysisJobIdViolationsGet200Response { 
    data?: Array<ApiV1ViolationsGet200ResponseDataInner>;
    meta?: ApiV1AnalysisJobsAnalysisJobIdViolationsGet200ResponseMeta;
}


