/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1ProjectsProjectIdBuildMetricsGet200ResponseMetricsInner } from './api-v1-projects-project-id-build-metrics-get200-response-metrics-inner';
import { ApiV1ProjectsProjectIdBuildMetricsGet200ResponseFilters } from './api-v1-projects-project-id-build-metrics-get200-response-filters';


export interface ApiV1ProjectsProjectIdBuildMetricsGet200Response { 
    metrics: Array<ApiV1ProjectsProjectIdBuildMetricsGet200ResponseMetricsInner>;
    filters: ApiV1ProjectsProjectIdBuildMetricsGet200ResponseFilters;
}


