/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1ProjectsPostRequestProject } from './api-v1-projects-post-request-project';


export interface ApiV1ProjectsPostRequest { 
    project: ApiV1ProjectsPostRequestProject;
}


