/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1ViolationsGet200ResponseMeta } from './api-v1-violations-get200-response-meta';
import { ApiV1ViolationsGet200ResponseDataInner } from './api-v1-violations-get200-response-data-inner';


export interface ApiV1ViolationsGet200Response { 
    data?: Array<ApiV1ViolationsGet200ResponseDataInner>;
    meta?: ApiV1ViolationsGet200ResponseMeta;
}


