/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiV1ProjectsProjectIdBuildMetricsPostRequestMetricsInner { 
    timestamp: string;
    duration_ms: number;
    is_initial_build: boolean;
    machine_hostname?: string;
    machine_platform?: string;
    machine_cpu_count?: number;
    machine_memory_total?: number;
    machine_memory_free?: number;
    process_node_version?: string;
    process_memory?: number;
    build_files_count?: number;
    build_output_dir?: string;
    build_error_count?: number;
    build_warning_count?: number;
    workspace_name?: string;
    workspace_project: string;
    workspace_environment: string;
    workspace_user: string;
    workspace_task?: string;
    branch_name?: string;
    commit_hash?: string;
}


