/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1ViolationsGet200ResponseDataInnerFileWithViolations } from './api-v1-violations-get200-response-data-inner-file-with-violations';


export interface ApiV1ViolationsGet200ResponseDataInner { 
    id?: number;
    rule_id?: string;
    rule_name?: string;
    line_number?: number;
    column?: number;
    match_text?: string;
    file_with_violations?: ApiV1ViolationsGet200ResponseDataInnerFileWithViolations;
}


