/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1FilesWithViolationsGet200ResponseMeta } from './api-v1-files-with-violations-get200-response-meta';
import { ApiV1FilesWithViolationsGet200ResponseDataInner } from './api-v1-files-with-violations-get200-response-data-inner';


export interface ApiV1FilesWithViolationsGet200Response { 
    data?: Array<ApiV1FilesWithViolationsGet200ResponseDataInner>;
    meta?: ApiV1FilesWithViolationsGet200ResponseMeta;
}


