/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1RuleGroupsGet200ResponseRuleGroupsInnerRulesInner } from './api-v1-rule-groups-get200-response-rule-groups-inner-rules-inner';


export interface ApiV1RuleGroupsIdGet200Response { 
    id?: number;
    name?: string;
    description?: string;
    rules?: Array<ApiV1RuleGroupsGet200ResponseRuleGroupsInnerRulesInner>;
}


