/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1ProjectsProjectIdRulesGet200ResponseRulesInner } from './api-v1-projects-project-id-rules-get200-response-rules-inner';


export interface ApiV1ProjectsProjectIdRulesGet200Response { 
    rules: Array<ApiV1ProjectsProjectIdRulesGet200ResponseRulesInner>;
}


