/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1ProjectsProjectIdBuildMetricsGet200ResponseMetricsInnerGit } from './api-v1-projects-project-id-build-metrics-get200-response-metrics-inner-git';
import { ApiV1ProjectsProjectIdBuildMetricsGet200ResponseMetricsInnerSystem } from './api-v1-projects-project-id-build-metrics-get200-response-metrics-inner-system';
import { ApiV1ProjectsProjectIdBuildMetricsGet200ResponseMetricsInnerInitialBuilds } from './api-v1-projects-project-id-build-metrics-get200-response-metrics-inner-initial-builds';


export interface ApiV1ProjectsProjectIdBuildMetricsGet200ResponseMetricsInner { 
    timestamp?: string;
    initial_builds?: ApiV1ProjectsProjectIdBuildMetricsGet200ResponseMetricsInnerInitialBuilds;
    hot_reloads?: ApiV1ProjectsProjectIdBuildMetricsGet200ResponseMetricsInnerInitialBuilds;
    system?: ApiV1ProjectsProjectIdBuildMetricsGet200ResponseMetricsInnerSystem;
    git?: ApiV1ProjectsProjectIdBuildMetricsGet200ResponseMetricsInnerGit;
}


