/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiV1ProjectsProjectIdBuildMetricsGet200ResponseMetricsInnerInitialBuilds { 
    avg_duration_sec?: any | null;
    min_duration_sec?: any | null;
    max_duration_sec?: any | null;
    build_count?: number;
    total_errors?: number;
    total_warnings?: number;
    avg_files_count?: any | null;
}


