/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1AuthWebauthnLoginAuthenticatePostRequestResponse } from './api-v1-auth-webauthn-login-authenticate-post-request-response';


export interface ApiV1AuthWebauthnLoginAuthenticatePostRequest { 
    id: string;
    rawId: string;
    type: ApiV1AuthWebauthnLoginAuthenticatePostRequestTypeEnum;
    response: ApiV1AuthWebauthnLoginAuthenticatePostRequestResponse;
}
export enum ApiV1AuthWebauthnLoginAuthenticatePostRequestTypeEnum {
    PUBLIC_KEY = 'public-key'
};




