/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1AnalysisJobsRuleHistoryGet200ResponseMeta } from './api-v1-analysis-jobs-rule-history-get200-response-meta';
import { ApiV1AnalysisJobsRuleHistoryGet200ResponseDataInner } from './api-v1-analysis-jobs-rule-history-get200-response-data-inner';


export interface ApiV1AnalysisJobsRuleHistoryGet200Response { 
    data: Array<ApiV1AnalysisJobsRuleHistoryGet200ResponseDataInner>;
    meta: ApiV1AnalysisJobsRuleHistoryGet200ResponseMeta;
}


