/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1ProjectsProjectIdRulesIdPatchRequestRule } from './api-v1-projects-project-id-rules-id-patch-request-rule';


export interface ApiV1ProjectsProjectIdRulesIdPatchRequest { 
    rule?: ApiV1ProjectsProjectIdRulesIdPatchRequestRule;
}


