/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiV1ProjectsProjectIdRulesGet200ResponseRulesInner { 
    id: number;
    name: string;
    description: string;
    enabled: boolean;
    created_at?: string;
    updated_at?: string;
}


