/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1ProjectsProjectIdBuildMetricsPost201ResponseResultsInner } from './api-v1-projects-project-id-build-metrics-post201-response-results-inner';


export interface ApiV1ProjectsProjectIdBuildMetricsPost201Response { 
    results: Array<ApiV1ProjectsProjectIdBuildMetricsPost201ResponseResultsInner>;
}


