/**
 * Sentinel API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1RuleGroupsGet200ResponseRuleGroupsInner } from './api-v1-rule-groups-get200-response-rule-groups-inner';


export interface ApiV1RuleGroupsGet200Response { 
    rule_groups: Array<ApiV1RuleGroupsGet200ResponseRuleGroupsInner>;
}


